networks:
  web:

services:
  hoe-jupyter:
    hostname: hoe-jupyter
    image: bo44arov/hoe-notebook
    command: start.sh jupyter lab --LabApp.token='' --NotebookApp.base_url=/jupyter
    networks:
      - web
    restart: always
  
  hoe-site:
    image: bo44arov/hoe-site
    ports:
      - 80:80
    networks:
      - web
    restart: always
